Add PanTro
popsim-consortium/stdpopsim pull request #1215
Opened 2022-04-12 16:53 UTC by xin-huang

In this pr, I added a demographic model for Pan troglodytes based on [Kuhlwilm et al. 2019](https://www.nature.com/articles/s41559-019-0881-7) Supplementary Table S2.2 column I and Table S3

Other parameters can be found in https://github.com/popsim-consortium/stdpopsim/issues/1000

2022-04-21 18:26 UTC, grahamgower requested changes
Hey @xin-huang. This looks great! The failing tests are just about code style, which can be fixed by using the pre-commit tool as described in the developer docs: https://popsim-consortium.github.io/stdpopsim-docs/latest/development.html#github-workflow

After that, I think this will be good to merge. It would be good to open an issue for the demographic model QC, separate to the species QC issue.

2022-04-24 09:47 UTC, xin-huang commented
Hi @grahamgower 
I fixed the code style. All tests are passed now.

2022-04-25 07:20 UTC, grahamgower approved these changes

2022-04-25 07:20 UTC, merged

2022-04-25 07:21 UTC, grahamgower commented
Thanks @xin-huang. Could you please open a new issue to track the QC for the BonoboGhost_4K19 demographic model?