Deprecate `length_multiplier`
popsim-consortium/stdpopsim pull request #1605
Opened 2024-12-16 19:12 UTC by nspope

Fixes #1349

2024-12-16 19:16 UTC, nspope commented
Linting error in the docs,
```
 diff --git a/docs/tutorial.rst b/docs/tutorial.rst
index 36a3cce..bc5d619 100644
--- a/docs/tutorial.rst
+++ b/docs/tutorial.rst
@@ -512,8 +512,9 @@ This provides both a ``size_history`` plot and a ``tubes`` visualization. E.g.
 .. code-block:: python
 
     import demesdraw
+
     graph = model.model.to_demes()
-    demesdraw.tubes(model.model.to_demes());
+    demesdraw.tubes(model.model.to_demes())
 
 Equivalent plots for all the available demographic models are also
 shown in the :ref:`sec_catalog`.
```

though I think the semicolon is intended here?

2024-12-16 19:40 UTC, nspope commented
I'd like to modify the tests so that they don't use `length_multiplier`, but forgot that it differs from `left` / `right` in that the latter keeps the original contig's coordinate system. This matters esp for SLiM, where the "masked" portions of a contig are actually simulated with recombination rate 0 (and can have impactful mutations added if there's a DFE).

2024-12-20 14:24 UTC, petrelharp requested changes
LGTM!

2024-12-20 14:24 UTC, petrelharp commented on CHANGELOG.rst
> +  contig, instead. (:user:`nspope`, :pr:`xxxx`)
```suggestion
  contig, instead. (:user:`nspope`, :pr:`1605`)
```

2024-12-20 14:24 UTC, petrelharp commented on stdpopsim/cli.py
> +        "recombination rates.",
```suggestion
        help="Deprecated: use left/right instead. Simulate a sequence of "
        "length l times the named chromosome's length using the named "
        "chromosome's mutation and recombination rates.",
```

2024-12-20 14:24 UTC, petrelharp commented on stdpopsim/species.py
> +            argument.
```suggestion
            cannot be used in conjunction with the ``genetic_map`` argument.
```

2024-12-20 18:42 UTC, nspope commented
Are we distinguishing 0.2.1 from 0.2.1a in the changelog? Looks like not, as the discretization bug fix went under 0.2.1a?

2024-12-21 01:39 UTC, merged