C. elegans genome & genetic map
popsim-consortium/stdpopsim pull request #910
Opened 2021-04-12 22:27 UTC by attrna

A follow-up PR to #904.

Note: The genetic map has only 3 columns.

2021-06-30 06:24 UTC, grahamgower requested changes
This looks very close @attrna. It would be great if you could rebase your PR onto the latest changes in the main branch (https://stdpopsim.readthedocs.io/en/latest/development.html#rebasing). Given the C. elegans species is now in, you'll no longer need to add the species definition here. The failing tests don't look too hard to solve either --- see comments below.

2021-06-30 06:24 UTC, grahamgower commented on stdpopsim/catalog/CaeEle/genetic_maps.py
> +    id="RockmanRIAIL",
One of the failing tests is complaining about the `id` used for the genetic map. See the "naming conventions" section of the dev docs: https://stdpopsim.readthedocs.io/en/latest/development.html#naming-conventions
The genetic map should be using coordinates that match a specific genome assembly, so the naming convention asks for the genome assembly to be part of the genetic map id.

2021-06-30 06:24 UTC, grahamgower commented on stdpopsim/catalog/CaeEle/genetic_maps.py
> +    file_pattern="C.elegans.Rockman.Kruglyak.2009.{id}.hapmap.txt",
It looks like the genetic map files in your tarball are inside a `genetic_map` subdirectory. So this needs to be part of the `file_pattern` too, or stdpopsim won't be able to find the files.
```suggestion
    file_pattern="genetic_map/C.elegans.Rockman.Kruglyak.2009.{id}.hapmap.txt",
```

2021-06-30 06:24 UTC, grahamgower commented on stdpopsim/catalog/CaeEle/genetic_maps.py
> +    url=("http://sesame.uoregon.edu/~ateterina/" "rockman2009_maps.tgz"),
The url here is short enough to fit on one line, so no need for the brackets and separate strings.
```suggestion
    url="http://sesame.uoregon.edu/~ateterina/rockman2009_maps.tgz",
```

2022-04-25 07:31 UTC, grahamgower commented
Hi @attrna. Are you still interested in having this work merged into stdpopsim? It looks like there's a bit of polishing needed, but it looks like you've already done most of the hard work.

2022-04-26 00:19 UTC, attrna commented
Hi @grahamgower! Yes, I do. I'm so sorry it took so long!
Please could you help me with that? Should I do rebasing or something else too as it's been a while since I did the PR?


Thank you!
Anastasia

2022-04-26 06:16 UTC, grahamgower commented
Yes, you'll definitely need to rebase, because there have been a lot of changes in the past 12 months. It would be great if you could also address the other small comments I made last year. There are lots of instructions in the [dev docs](https://popsim-consortium.github.io/stdpopsim-docs/latest/development.html) for rebasing, but this can be a pain even for experienced git users. So if you get tangled just let me know and I can have a go at it.

2022-04-30 00:29 UTC, attrna commented
Hi @grahamgower! I made all the small changes you suggested above, but I'm not sure what commits to squash and where exactly to rebase (how to pick the base for rebasing). I guess I should not commit the changes before rebasing, is it right? Please could you help me with that?

2022-05-01 08:19 UTC, grahamgower commented
Hi @attrna. You will need to commit your changes before rebasing. Check the dev docs for additional info: https://popsim-consortium.github.io/stdpopsim-docs/latest/development.html#rebasing

* After committing, fetch the latest changes from the stdpopsim upstream repository. `git fetch upstream`, where "upstream" is the name of the upstream repository. This will probably be called "upstream" but you can double check by looking for the popsim-consortium/stdpopsim repository in the output of `git remote -v`.
* Make a copy of your working branch (`git branch celegansgenmap-copy`), so if you get stuck you can reset your working branch to match the copy (`git reset --hard celegansgenmap-copy`). You can also push your working branch to your github fork as a backup (it should also appear here in your pull request as usual).
* rebase onto the "upstream/main" branch (where "upstream" is once again the name for the upstream repository). `git rebase -i upstream/main`.
* Don't worry about squashing anything right now, just see if the rebase works. You can rebase again later and squash things.
* If you get conflicts during rebasing, you'll need to manually edit the conflicting files to fix things. Make sure to carefully read the messages that git gives you, and calling `git status` between edits can be helpful.
* If all goes well, you can try rebasing again and squashing commits. "One idea, one commit" is a good rule of thumb. The main idea for your pull request is to add the genetic map for CaeEle, so probably one commit is fine.

2022-05-01 16:53 UTC, attrna commented
Hi @grahamgower! Thank you so much for your help! I did it, probably I messed something up because it doesn't let me push. Should I do git pull before all that?

```
anastasia@Anastasias-MacBook-Pro:CaeEle$ git push
To https://github.com/attrna/stdpopsim
 ! [rejected]        celegansgenmap -> celegansgenmap (non-fast-forward)
error: failed to push some refs to 'https://github.com/attrna/stdpopsim'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details  
```

2022-05-01 17:17 UTC, attrna commented
It seems that every time I'm doing "git rebase -i upstream/main" it finds some conflicts and I don't get how to resolve them, because it's basically the old version on the file.

2022-05-02 07:42 UTC, merged

2022-05-02 07:44 UTC, grahamgower commented
Thanks @attrna. I rebased for you and *force pushed* the branch back to the github repository. I also had issues with the rebase because of the same contents being present multiple times, so I'm not sure what happened there. After rebasing, one usually has to `git push -f` to force push the branch.

2022-05-02 15:57 UTC, attrna commented
Thank you so much, @grahamgower!!